<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Report {{ $report->id }}</title>
</head>
<body>
    <h2>Report #{{ $report->id }}</h2>
    <p><strong>Type:</strong> {{ ucfirst($report->type) }}</p>
    <p><strong>Periode:</strong> {{ $report->periode_awal }} - {{ $report->periode_akhir }}</p>
    <p><strong>Amount:</strong> Rp {{ number_format($report->amount,0,',','.') }}</p>
    <p><strong>Generated By:</strong> {{ $report->generate_by }}</p>
    <p><strong>Tanggal Dibuat:</strong> {{ $report->created_at }}</p>
</body>
</html>
