
@extends('layouts.app')
@section('content')
<div class="p-6">
  <h1 class="text-2xl font-bold mb-6">Reports (readonly)</h1>
  <!-- Table Laporan -->
  <div class="overflow-x-auto bg-white rounded-lg shadow">
    <table class="w-full border border-gray-300 rounded-lg">
      <thead class="bg-gray-200">
        <tr>
          <th class="px-4 py-2 border">#</th>
          <th class="px-4 py-2 border">Periode</th>
          <th class="px-4 py-2 border">Type</th>
          <th class="px-4 py-2 border">Amount</th>
          <th class="px-4 py-2 border">Generated By</th>
        </tr>
      </thead>
      <tbody>
        @forelse($reports as $report)
        <tr class="hover:bg-gray-50">
          <td class="px-4 py-2 border">{{ $loop->iteration }}</td>
          <td class="px-4 py-2 border">{{ $report->periode_awal }} - {{ $report->periode_akhir }}</td>
          <td class="px-4 py-2 border">{{ $report->type }}</td>
          <td class="px-4 py-2 border">{{ number_format($report->amount,0,',','.') }}</td>
          <td class="px-4 py-2 border">{{ $report->generate_by }}</td>
        </tr>
        @empty
        <tr>
          <td colspan="5" class="text-center py-4">No reports found</td>
        </tr>
        @endforelse
      </tbody>
    </table>
  </div>

  <div class="mt-4">
    {{ $reports->links() }}
  </div>
</div>
@endsection
