<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>{{ $title ?? 'Laporan' }}</title>
    <style>
        body {
            font-family: DejaVu Sans, sans-serif;
            font-size: 12px;
        }
        .header {
            text-align: center;
            margin-bottom: 20px;
        }
        .header h2 {
            margin: 0;
        }
        .table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 10px;
        }
        .table th, .table td {
            border: 1px solid #000;
            padding: 6px;
            text-align: left;
        }
        .table th {
            background: #f2f2f2;
        }
        .footer {
            margin-top: 30px;
            font-size: 11px;
            text-align: right;
        }
    </style>
</head>
<body>
    <div class="header">
        <h2>{{ $title ?? 'Laporan Data' }}</h2>
        <p>Tanggal: {{ $date ?? now()->format('d-m-Y') }}</p>
    </div>

    @if(isset($transactions) && count($transactions) > 0)
        <table class="table">
            <thead>
                <tr>
                    <th>No</th>
                    <th>Invoice</th>
                    <th>Customer</th>
                    <th>Supplier</th>
                    <th>Total</th>
                    <th>Status</th>
                    <th>Tanggal</th>
                </tr>
            </thead>
            <tbody>
                @foreach($transactions as $i => $trx)
                    <tr>
                        <td>{{ $i+1 }}</td>
                        <td>{{ $trx->invoice }}</td>
                        <td>{{ $trx->customer->name ?? '-' }}</td>
                        <td>{{ $trx->supplier->name ?? '-' }}</td>
                        <td>{{ number_format($trx->total, 0, ',', '.') }}</td>
                        <td>{{ ucfirst($trx->status) }}</td>
                        <td>{{ \Carbon\Carbon::parse($trx->date)->format('d-m-Y') }}</td>
                    </tr>
                @endforeach
            </tbody>
        </table>
    @else
        <p>Tidak ada data ditemukan.</p>
    @endif

    <div class="footer">
        <p>Generated by Sistem - {{ now()->format('d-m-Y H:i') }}</p>
    </div>
</body>
</html>
