@extends('layouts.app')

@section('content')
<div class="p-6">
    <h1 class="text-2xl font-bold mb-4">Supplier Reports</h1>

    <!-- Alert Success -->
    @if(session('success'))
        <div class="bg-green-100 text-green-800 p-2 mb-4 rounded">
            {{ session('success') }}
        </div>
    @endif

    <!-- Reports Table -->
    <div class="overflow-x-auto bg-white rounded shadow-sm">
        <table class="min-w-full border-collapse border border-gray-200">
            <thead class="bg-gray-100">
                <tr>
                    <th class="border px-3 py-2">ID</th>
                    <th class="border px-3 py-2">Type</th>
                    <th class="border px-3 py-2">Periode</th>
                    <th class="border px-3 py-2">Amount</th>
                    <th class="border px-3 py-2">Generated By</th>
                    <th class="border px-3 py-2">Actions</th>
                </tr>
            </thead>
            <tbody>
                @forelse($reports as $report)
                <tr class="text-center">
                    <td class="border px-3 py-2">{{ $report->id }}</td>
                    <td class="border px-3 py-2">{{ ucfirst($report->type) }}</td>
                    <td class="border px-3 py-2">{{ $report->periode_awal }} - {{ $report->periode_akhir }}</td>
                    <td class="border px-3 py-2">{{ $report->amount }}</td>
                    <td class="border px-3 py-2">{{ $report->generate_by }}</td>
                    <td class="border px-3 py-2">
                        <a href="{{ route('backend.supplier.reports.download', $report->id) }}" class="text-blue-600 hover:underline">Download</a>
                    </td>
                </tr>
                @empty
                <tr>
                    <td colspan="6" class="border px-3 py-2 text-center">No reports found.</td>
                </tr>
                @endforelse
            </tbody>
        </table>
    </div>

    <!-- Pagination -->
    <div class="mt-4">
        {{ $reports->links() }}
    </div>
</div>
@endsection
