@extends('layouts.app')
@section('content')
<div class="p-6">
  <h1 class="text-2xl font-bold mb-6">Reports</h1>

  <!-- Filter -->
  <form method="GET" class="flex space-x-4 mb-6">
    <input type="date" name="start_date" value="{{ request('start_date') }}" class="px-3 py-2 border rounded">
    <input type="date" name="end_date" value="{{ request('end_date') }}" class="px-3 py-2 border rounded">
    <select name="type" class="px-3 py-2 border rounded">
      <option value="all">All Reports</option>
      <option value="purchase" {{ request('type')=='purchase' ? 'selected':'' }}>Purchases</option>
      <option value="stock" {{ request('type')=='stock' ? 'selected':'' }}>Stock</option>
      <option value="customer" {{ request('type')=='customer' ? 'selected':'' }}>Customer</option>
      <option value="supplier" {{ request('type')=='supplier' ? 'selected':'' }}>Supplier</option>
    </select>
    <button class="px-4 py-2 bg-blue-600 text-white rounded">Filter</button>
  </form>

  <!-- Table Laporan -->
  <div class="overflow-x-auto bg-white rounded-lg shadow">
    <table class="w-full">
      <thead class="bg-gray-100">
        <tr>
          <th class="px-4 py-2">#</th>
          <th class="px-4 py-2">Periode</th>
          <th class="px-4 py-2">Type</th>
          <th class="px-4 py-2">Amount</th>
          <th class="px-4 py-2">Generated By</th>
        </tr>
      </thead>
      <tbody>
        @forelse($reports as $report)
        <tr class="hover:bg-gray-50">
          <td class="px-4 py-2">{{ $loop->iteration }}</td>
          <td class="px-4 py-2">{{ $report->periode_awal }} - {{ $report->periode_akhir }}</td>
          <td class="px-4 py-2 capitalize">{{ $report->type }}</td>
          <td class="px-4 py-2">{{ number_format($report->amount,0,',','.') }}</td>
          <td class="px-4 py-2">{{ $report->generate_by }}</td>
        </tr>
        @empty
        <tr>
          <td colspan="5" class="text-center py-4">No reports found</td>
        </tr>
        @endforelse
      </tbody>
    </table>
  </div>

  <div class="mt-4">
    {{ $reports->links() }}
  </div>
</div>
@endsection
